from solvers.days.y2025.day_07 import Day07Solver
from solvers.storage import storage

def test_part1():
    example = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""
    
    solver = Day07Solver(example)
    result = solver.part1()
    print(f"Example Part 1 Result: {result}")
    assert result == 21, f"Expected 21, got {result}"

if __name__ == "__main__":
    test_part1()
    
    # Load real input
    try:
        real_input = storage.load_input(2025, 7)
        solver = Day07Solver(real_input)
        print(f"Real Part 1 Result: {solver.part1()}")
    except Exception as e:
        print(f"Could not run on real input: {e}")

def test_part2():
    example = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""
    
    solver = Day07Solver(example)
    result = solver.part2()
    print(f"Example Part 2 Result: {result}")
    assert result == 40, f"Expected 40, got {result}"

if __name__ == "__main__":
    test_part1()
    test_part2()
    
    # Load real input
    try:
        real_input = storage.load_input(2025, 7)
        solver = Day07Solver(real_input)
        print(f"Real Part 1 Result: {solver.part1()}")
        print(f"Real Part 2 Result: {solver.part2()}")
    except Exception as e:
        print(f"Could not run on real input: {e}")
